# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays. For more control, add individual board + shield combinations
# to the `include` property.

include:
  - board: nice_nano_v2
    shield: silakka54_left
    keymap: silakka54_custom
  - board: nice_nano_v2
    shield: silakka54_right
    keymap: silakka54_custom
