name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nice_nano_v2
            shield: silakka54_left
            artifact-name: silakka54_left_firmware
          - board: nice_nano_v2
            shield: silakka54_right
            artifact-name: silakka54_right_firmware
