name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    strategy:
      matrix:
        include:
          - board: nice_nano_v2
            shield: silakka54_left
          - board: nice_nano_v2
            shield: silakka54_right
    steps:
      - name: Checkout ZMK
        uses: actions/checkout@v3
        with:
          repository: zmkfirmware/zmk
          ref: main

      - name: Checkout user config
        uses: actions/checkout@v3
        with:
          path: config

      - name: Build
        run: west build -s zmk/app -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }}

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: build/zephyr/zmk.uf2
